config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "/sign-up" => "registrations#new", as: :signup
  post "/sign-up" => "registrations#create"
  get "/sign-in" => "authentication#new", as: :signin
  post "/sign-in" => "authentication#create"
  get "/sign-out" => "authentication#destroy", as: :signout

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  before_action :authenticate_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  private
    def authenticate_user
      redirect_to(signin_path) unless current_user
    end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_action :authenticate_user

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Username/Password is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :email,
        :password,
        :password_confirmation,
      )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # Allow access to pages in this controller without authenticating user first.
  skip_before_action :authenticate_user

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<h1>Sign In</h1>


<%= form_tag signin_path do |f| %>
<%= flash[:alert] %>


<div>
  <%= label_tag :email %>
</div>
<div>
  <%= email_field_tag :email %>
</div>

<div>
  <%= label_tag :password %>
</div>
<div>
  <%= password_field_tag :password %>
</div>

<div>
  <%= submit_tag "Sign in" %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAuthTemplate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <% if current_user %>
      <%= link_to "Sign Out", signout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Sign In", signin_path %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>